name: idbi-invoice-recorder-challenge

networks:
  main-net:
    driver: bridge

volumes:
  data:
    driver: local

services:
  web:
    build: # Construcción personalizada desde un Dockerfile
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app:cached"
    ports:
      - "8080:80"
    networks:
      - main-net
    environment:
      NODE_VERSION: 20 # Última versión LTS de Node.js

  db:
    image: mysql:8.1 # Versión más reciente de MySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: idbi_invoice_recorder_challenge_db
      MYSQL_ROOT_PASSWORD: cHkQPaZashJ8avB7
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    volumes:
      - "data:/var/lib/mysql"
    networks:
      - main-net

  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - main-net
